name: Push new image to Quay.io registry

on:
  push:
    branches:
      - main
    paths:
      - 'backend/data_processing/*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: elisaohtuprojekti-backend
          tags: latest
          context: backend/data_processing/
          containerfiles: backend/data_processing/Containerfile

      - name: Push image to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{env.QUAY_REPOSITORY}}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
