name: Sync and push backend to version.helsinki.fi

on:
  push:
    branches:
      - main
    paths:
      - 'backend/*'

jobs:
  sync-and-push:
    name: Sync and push backend to version.helsinki.fi
    runs-on: ubuntu-latest
    environment: production

    env:
      SOURCE_FOLDER: 'backend'
      TARGET_FOLDER: 'gitlab_temp'
      WORK_ROOT: '/home/runner/work'
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
    
      - name: Clone repo from ${{ vars.GITLAB_URL }}
        run: |
            git clone -b main --depth 1 https://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ vars.GITLAB_URL }}.git "$WORK_ROOT/$TARGET_FOLDER"

      - name: Rsync data between repos
        run: |
            rsync -av --delete "$SOURCE_FOLDER" "$WORK_ROOT/$TARGET_FOLDER/"

      - name: Push changes to ${{ vars.GITLAB_URL }}
        run: |
            cd "$WORK_ROOT/$TARGET_FOLDER"

            git config user.name "github-actions[bot]"
            git config user.email "actions@github.com"

            git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@${{ vars.GITLAB_URL }}

            git add *
            git commit -m "Sync ${GITHUB_SHA}"
            git push gitlab main
