name: Push to Quay.io registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: elisaohtuprojekti-backend
          tags: staging ${{ github.sha }}
          context: backend/data_processing/
          containerfiles: backend/data_processing/Containerfile

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: latest
          registry: quay.io/repository/ohtuprojekti
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Test Quay.io login
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | buildah login -u "${{ secrets.REGISTRY_USERNAME }}" quay.io --password-stdin
